# Generated by Django 5.0.4 on 2024-06-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_vigente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20, verbose_name='Estado'),
        ),
    ]
