# Generated by Django 4.0 on 2024-02-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_departamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
