# Generated by Django 4.1 on 2024-02-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_delete_departamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CAMPOS',
        ),
    ]
