# Generated by Django 4.1 on 2024-02-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_delete_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=10)),
                ('analista', models.CharField(max_length=50)),
            ],
        ),
    ]
