# Generated by Django 4.1 on 2024-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campos',
            name='analista',
            field=models.CharField(max_length=50, verbose_name='Nombre analista'),
        ),
        migrations.AlterField(
            model_name='campos',
            name='cedula',
            field=models.IntegerField(verbose_name='Cedula'),
        ),
    ]
