# Generated by Django 4.0 on 2024-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.CharField(max_length=50, unique=True, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name_plural': 'Habilidad de Empleado',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['departamento'], 'verbose_name_plural': 'Empleado en Departamentos'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Apellidos'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('job', 'first_name')},
        ),
    ]
