# Generated by Django 4.1 on 2024-02-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
