# Generated by Django 4.1 on 2024-02-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hbailidades',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
    ]
