# Generated by Django 4.1 on 2024-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_hbailidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidades',
            name='habilidad',
            field=models.CharField(max_length=30, verbose_name='Habilidad'),
        ),
    ]
