# Generated by Django 4.1 on 2024-02-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_habilidades_habilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='hbailidades',
            new_name='habilidades',
        ),
    ]
