# Generated by Django 4.1 on 2024-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_rename_hbailidades_empleado_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad_empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, unique=True, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad de Empleado',
                'verbose_name_plural': 'Habilidades de los Empleados',
            },
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.habilidad_empleados'),
        ),
    ]
