# Generated by Django 4.0 on 2024-02-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Departamento'},
        ),
    ]
