# Generated by Django 4.1 on 2024-02-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_empleado_unique_together_and_more'),
        ('departamento', '0002_alter_departamento_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
