# Generated by Django 5.0.4 on 2024-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificaion', models.BigIntegerField(verbose_name='Identificacion')),
                ('nombres', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('edad', models.BigIntegerField(verbose_name='Edad')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Creacion')),
            ],
        ),
    ]
